config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shots
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shot.rb
class Shot < ApplicationRecord
  belongs_to :user
  mount_uploader :user_shot, UserShotUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shots
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  before_action :set_shot, only: %i[show edit update destroy like unlike]
  before_action :authenticate_user!, only: %i[edit update destroy like unlike]
  impressionist actions: [:show], unique: %i[impressionable_type impressionable_id session_hash]

  # GET /shots or /shots.json
  def index
    @shots = Shot.all.order('created_at DESC')
  end

  # GET /shots/1 or /shots/1.json
  def show; end

  # GET /shots/new
  def new
    @shot = current_user.shots.build
  end

  # GET /shots/1/edit
  def edit; end

  # POST /shots or /shots.json
  def create
    @shot = Shot.new(shot_params)

    respond_to do |format|
      if @shot.save
        format.html { redirect_to shot_url(@shot), notice: 'Shot was successfully created.' }
        format.json { render :show, status: :created, location: @shot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shots/1 or /shots/1.json
  def update
    respond_to do |format|
      if @shot.update(shot_params)
        format.html { redirect_to shot_url(@shot), notice: 'Shot was successfully updated.' }
        format.json { render :show, status: :ok, location: @shot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shots/1 or /shots/1.json
  def destroy
    @shot.destroy
    respond_to do |format|
      format.html { redirect_to shots_url, notice: 'Shot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @shot.liked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { render layout: false }
    end
  end

  def unlike
    @shot.unlike_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { render layout: false }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_shot
    @shot = Shot.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def shot_params
    params.require(:shot).permit(:title, :description, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/views/home/index.html.erb
<h1 class="title button is-success">Home#index</h1>
<button type="" class=" button is-primary"> presss me </button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DribbbleClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    
    <%= render "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
	<% if flash[:notice] %>
    	<div class="notification is-primary global-notification">
  	  	<p class="notice"><%= notice %></p>
    	</div>
   	<% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class:"navbar-item" do %>
      <h1 class="title is-5 has-text-white">Dribbble Clone</h1>
    <% end  %>
    <div class="navbar-burger burger" data-target="navbar">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbar" class="navbar-menu">

    <div class="navbar-start">
      <div class="navbar-item">
        <div class="field is-grouped">
          <p class="control">
          <%= link_to 'Shots', root_path , class:"button is-dark" %>
          </p>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">
            <p class="control">
            <%= link_to new_shot_path, class:"button is-primary"  do %>
              <span class="icon is-small"><i class="fa fa-upload"></i></span>
              <span>New Shot</span>
            </p>
            <p class="control">
            <%= link_to current_user.name, edit_user_registration_path, class:"button is-dark" %>
            </p>
            <p class="control">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"button is-dark" %>
            </p>
          <% else %>
            <p class="control">
            <%= link_to "Sign In", new_user_session_path, class:"button is-dark" %>
            </p>
            <p class="control">
            <%= link_to "Sign up", new_user_registration_path, class:"button is-dark"%>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav> 

app/views/shots/_form.html.erb
<%= form_with(model: shot) do |form| %>
  <% if shot.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shot.errors.count, "error") %> prohibited this shot from being saved:</h2>

      <ul>
        <% shot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shots/_shot.html.erb
<div id="<%= dom_id shot %>">
  <p>
    <strong>Title:</strong>
    <%= shot.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= shot.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= shot.user_id %>
  </p>

</div>

app/views/shots/edit.html.erb
<h1>Editing shot</h1>

<%= render "form", shot: @shot %>

<br>

<div>
  <%= link_to "Show this shot", @shot %> |
  <%= link_to "Back to shots", shots_path %>
</div>

app/views/shots/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shots</h1>

<div id="shots">
  <% @shots.each do |shot| %>
    <%= render shot %>
    <p>
      <%= link_to "Show this shot", shot %>
    </p>
  <% end %>
</div>

<%= link_to "New shot", new_shot_path %>

app/views/shots/new.html.erb
<h1>New shot</h1>

<%= render "form", shot: @shot %>

<br>

<div>
  <%= link_to "Back to shots", shots_path %>
</div>

app/views/shots/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shot %>

<div>
  <%= link_to "Edit this shot", edit_shot_path(@shot) %> |
  <%= link_to "Back to shots", shots_path %>

  <%= button_to "Destroy this shot", @shot, method: :delete %>
</div>